services:
  patient-service-db:
    image: postgres:17
    container_name: patient-service-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - patient-service-db-data:/var/lib/postgresql/data
    networks:
      - internal-network
      
  patient-service:
    #image: patient-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    depends_on:
      - patient-service-db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - "4000:4000"
    networks:
      - internal-network
volumes:
  patient-service-db-data:
    
networks:
  internal-network: